import { IConfirmOptions, INotifyOptions, IReportOptions } from "notiflix";

interface INotiflixInit {
    notify: INotifyOptions,
    confirm: IConfirmOptions,
    report: IReportOptions
}

export function getInitNotiflixConfigs(): INotiflixInit {
    return {
        notify: {
            width: '280px',
            position: 'right-top',
            distance: '10px',
            opacity: 1,
            borderRadius: '5px',
            rtl: false,
            timeout: 2000,
            backOverlay: false,
            backOverlayColor: 'rgba(0,0,0,0.5)',
            plainText: true,
            showOnlyTheLastOne: false,
            clickToClose: true,
            pauseOnHover: true,
            ID: 'NotiflixNotify',
            className: 'notiflix-notify',
            zindex: 4001,
            fontFamily: 'Quicksand',
            fontSize: '13px',
            cssAnimation: true,
            cssAnimationDuration: 400,
            cssAnimationStyle: 'fade',
            closeButton: true,
            useIcon: true,
            useFontAwesome: true,
            fontAwesomeIconStyle: 'basic',
            fontAwesomeIconSize: '34px',
            success: {
                background: '#32c682',
                textColor: '#fff',
                childClassName: 'notiflix-notify-success',
                notiflixIconColor: 'rgba(0,0,0,0.2)',
                fontAwesomeClassName: 'fa fa-thumbs-up',
                fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
                backOverlayColor: 'rgba(50,198,130,0.2)',
            },
            failure: {
                background: '#ff5549',
                textColor: '#fff',
                childClassName: 'notiflix-notify-failure',
                notiflixIconColor: 'rgba(0,0,0,0.2)',
                fontAwesomeClassName: 'fa fa-times-circle',
                fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
                backOverlayColor: 'rgba(255,85,73,0.2)',
            },
            warning: {
                background: '#eebf31',
                textColor: '#fff',
                childClassName: 'notiflix-notify-warning',
                notiflixIconColor: 'rgba(0,0,0,0.2)',
                fontAwesomeClassName: 'fa fa-hand-spock-o',
                fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
                backOverlayColor: 'rgba(238,191,49,0.2)',
            },
            info: {
                background: '#ffbe33',
                textColor: '#fff',
                childClassName: 'notiflix-notify-info',
                notiflixIconColor: 'rgba(0,0,0,0.2)',
                fontAwesomeClassName: 'fa fa-hand-spock-o',
                fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
                backOverlayColor: 'rgba(38,192,211,0.2)',
            },
        },
        confirm: {
            className: 'notiflix-confirm',
            width: '300px',
            zindex: 4003,
            position: 'center',
            distance: '10px',
            backgroundColor: '#f8f8f8',
            borderRadius: '25px',
            backOverlay: true,
            backOverlayColor: 'rgba(0,0,0,0.5)',
            rtl: false,
            fontFamily: 'Quicksand',
            cssAnimation: true,
            cssAnimationDuration: 300,
            cssAnimationStyle: 'fade',
            plainText: true,
            titleColor: '#eebf31',
            titleFontSize: '16px',
            titleMaxLength: 34,
            messageColor: '#1e1e1e',
            messageFontSize: '14px',
            messageMaxLength: Infinity,
            buttonsFontSize: '15px',
            buttonsMaxLength: 34,
            okButtonColor: '#f8f8f8',
            okButtonBackground: '#eebf31',
            cancelButtonColor: '#f8f8f8',
            cancelButtonBackground: '#a9a9a9',
        },
        report: {
            className: 'notiflix-report',
            width: '320px',
            backgroundColor: '#f8f8f8',
            borderRadius: '25px',
            rtl: false,
            zindex: 4002,
            backOverlay: true,
            backOverlayColor: 'rgba(0,0,0,0.5)',
            backOverlayClickToClose: false,
            fontFamily: 'Quicksand',
            svgSize: '110px',
            plainText: true,
            titleFontSize: '16px',
            titleMaxLength: 34,
            messageFontSize: '13px',
            messageMaxLength: 400,
            buttonFontSize: '14px',
            buttonMaxLength: 34,
            cssAnimation: true,
            cssAnimationDuration: 360,
            cssAnimationStyle: 'fade',
            success: {
                svgColor: '#eebf31',
                titleColor: '#1e1e1e',
                messageColor: '#242424',
                buttonBackground: '#eebf31',
                buttonColor: '#fff',
                backOverlayColor: 'rgba(50,198,130,0.2)',
            },
            failure: {
                svgColor: '#ff5549',
                titleColor: '#1e1e1e',
                messageColor: '#242424',
                buttonBackground: '#ff5549',
                buttonColor: '#fff',
                backOverlayColor: 'rgba(255,85,73,0.2)',
            },
            warning: {
                svgColor: '#eebf31',
                titleColor: '#1e1e1e',
                messageColor: '#242424',
                buttonBackground: '#eebf31',
                buttonColor: '#fff',
                backOverlayColor: 'rgba(238,191,49,0.2)',
            },
            info: {
                svgColor: '#26c0d3',
                titleColor: '#1e1e1e',
                messageColor: '#242424',
                buttonBackground: '#26c0d3',
                buttonColor: '#fff',
                backOverlayColor: 'rgba(38,192,211,0.2)',
            },
        }
    }
}